# Generated by Django 4.1.3 on 2022-12-22 18:23
# https://docs.djangoproject.com/en/4.1/topics/migrations/#data-migrations

from django.db import migrations
import csv


def import_schools(apps, schema_editor):
    School = apps.get_model("dissertations", "School")
    with open("aha-data/schools.csv") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            school = School(
                id=row["id"], aha_school_id=row["aha_school_id"], name=row["school"]
            )
            school.save()


def truncate_schools(apps, schema_editor):
    School = apps.get_model("dissertations", "School")
    School.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dissertations", "0001_model_school"),
    ]

    operations = [migrations.RunPython(import_schools, truncate_schools)]
