# Generated by Django 4.1.3 on 2022-12-22 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissertations", "0002_seed_schools"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scholar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "aha_scholar_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="The identifier used by the AHA for a school",
                        null=True,
                        unique=True,
                        verbose_name="AHA scholar ID",
                    ),
                ),
                (
                    "aha_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        editable=False,
                        help_text="The name provided in the AHA dataset",
                        max_length=200,
                        null=True,
                        verbose_name="AHA name",
                    ),
                ),
                (
                    "name_first",
                    models.CharField(max_length=200, verbose_name="First name"),
                ),
                (
                    "name_middle",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=200,
                        verbose_name="Middle name",
                    ),
                ),
                (
                    "name_last",
                    models.CharField(max_length=200, verbose_name="Last name"),
                ),
                (
                    "name_suffix",
                    models.CharField(
                        blank=True, default=None, max_length=200, verbose_name="Suffix"
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="ORCID in 0000-0000-0000-0000 format",
                        max_length=19,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\d{4}-\\d{4}-\\d{4}-\\d{4}"
                            )
                        ],
                        verbose_name="ORCID",
                    ),
                ),
            ],
            options={
                "ordering": ["name_last", "name_first", "name_middle"],
            },
        ),
    ]
