# Generated by Django 4.1.3 on 2022-12-22 21:30

from django.db import migrations
import csv


def import_scholars(apps, schema_editor):
    Scholar = apps.get_model("dissertations", "Scholar")
    to_import = []
    with open("aha-data/scholars.csv") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            scholar = Scholar(
                id=row["id"],
                aha_scholar_id=row["aha_scholar_id"],
                aha_name=row["name"],
                name_first=row["name_first"],
                name_middle=row["name_middle"],
                name_last=row["name_last"],
                name_suffix=row["name_suffix"],
                orcid=row["orcid"],
            )
            to_import.append(scholar)
    Scholar.objects.bulk_create(to_import)

    # Add ORCIDs for people I know
    Scholar.objects.filter(id=16756).update(
        orcid="0000-0001-5103-6917"
    )  # Lincoln Mullen
    Scholar.objects.filter(id=22028).update(orcid="0000-0001-9225-8938")  # Abby Mullen
    Scholar.objects.filter(id=21496).update(orcid="0000-0002-4165-9202")  # Kellen Funk
    Scholar.objects.filter(id=8499).update(orcid="0000-0002-7202-2570")  # Rosie Zagarri
    Scholar.objects.filter(id=2514).update(
        orcid="0000-0002-7700-3109"
    )  # Jonathan Sarna
    Scholar.objects.filter(id=15550).update(
        orcid="0000-0003-4158-6186"
    )  # Jason Heppler


def truncate_scholars(apps, schema_editor):
    Scholar = apps.get_model("dissertations", "Scholar")
    Scholar.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dissertations", "0003_scholar"),
    ]

    operations = [migrations.RunPython(import_scholars, truncate_scholars)]
