# Generated by Django 4.1.3 on 2022-12-22 23:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dissertations", "0004_seed_scholars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholar",
            name="aha_scholar_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="The identifier used by the AHA for a scholar",
                null=True,
                unique=True,
                verbose_name="AHA scholar ID",
            ),
        ),
        migrations.CreateModel(
            name="Dissertation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "aha_dissertation_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        help_text="The identifier used by the AHA for a dissertation",
                        null=True,
                        unique=True,
                        verbose_name="AHA dissertation ID",
                    ),
                ),
                ("title", models.CharField(max_length=2000)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1700, "The year must be after 1700"
                            ),
                            django.core.validators.MaxValueValidator(
                                2022, "The year must be the current year or before"
                            ),
                        ],
                    ),
                ),
                (
                    "aha_author_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA author ID",
                    ),
                ),
                (
                    "aha_school_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA school ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dissertations.scholar",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dissertations.school",
                    ),
                ),
            ],
        ),
    ]
