# Generated by Django 4.1.3 on 2022-12-22 23:35

from django.db import migrations
import csv


def import_dissertations(apps, schema_editor):
    Dissertation = apps.get_model("dissertations", "Dissertation")
    to_import = []
    with open("aha-data/dissertations.csv") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            diss = Dissertation(
                id=row["id"],
                aha_dissertation_id=row["aha_dissertation_id"],
                title=row["title"],
                year=row["year"],
                author_id=row["author_id"],
                aha_author_id=row["aha_author_id"],
                school_id=row["school_id"],
                aha_school_id=row["aha_school_id"],
            )
            to_import.append(diss)
    Dissertation.objects.bulk_create(to_import)


def truncate_dissertations(apps, schema_editor):
    Dissertation = apps.get_model("dissertations", "Dissertation")
    Dissertation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dissertations", "0005_alter_scholar_aha_scholar_id_dissertation"),
    ]

    operations = [migrations.RunPython(import_dissertations, truncate_dissertations)]
