# Generated by Django 4.1.3 on 2022-12-23 00:22

from django.db import migrations
import csv


def import_committees(apps, schema_editor):
    CommitteeMember = apps.get_model("dissertations", "CommitteeMember")
    to_import = []
    with open("aha-data/committee-members.csv") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            member = CommitteeMember(
                dissertation_id=row["dissertation_id"],
                scholar_id=row["scholar_id"],
                role=row["role"],
                aha_scholar_id=row["aha_scholar_id"],
                aha_dissertation_id=row["aha_dissertation_id"],
            )
            to_import.append(member)
    CommitteeMember.objects.bulk_create(to_import)


def truncate_committees(apps, schema_editor):
    CommitteeMember = apps.get_model("dissertations", "CommitteeMember")
    CommitteeMember.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dissertations", "0007_committeemember"),
    ]

    operations = [migrations.RunPython(import_committees, truncate_committees)]


#
