# Generated by Django 4.1.3 on 2024-03-12 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissertations", "0008_seed_committees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dissertation",
            name="year",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1700, "The year must be after 1700"
                    ),
                    django.core.validators.MaxValueValidator(
                        2024, "The year must be the current year or before"
                    ),
                ],
            ),
        ),
    ]
