# Generated by Django 4.1.3 on 2022-12-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "aha_school_id",
                    models.BigIntegerField(
                        help_text="The identifier used by the AHA for a school",
                        unique=True,
                        verbose_name="AHA school ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the school", max_length=200
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
