# Generated by Django 5.2.5 on 2025-08-26 18:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scholar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "aha_scholar_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="The identifier used by the AHA for a scholar",
                        null=True,
                        unique=True,
                        verbose_name="AHA scholar ID",
                    ),
                ),
                (
                    "aha_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        editable=False,
                        help_text="The name provided in the AHA dataset",
                        max_length=200,
                        null=True,
                        verbose_name="AHA name",
                    ),
                ),
                (
                    "name_first",
                    models.CharField(max_length=200, verbose_name="First name"),
                ),
                (
                    "name_middle",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=200,
                        verbose_name="Middle name",
                    ),
                ),
                (
                    "name_last",
                    models.CharField(max_length=200, verbose_name="Last name"),
                ),
                (
                    "name_suffix",
                    models.CharField(
                        blank=True, default=None, max_length=200, verbose_name="Suffix"
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="ORCID in 0000-0000-0000-0000 format",
                        max_length=19,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\d{4}-\\d{4}-\\d{4}-\\d{4}"
                            )
                        ],
                        verbose_name="ORCID",
                    ),
                ),
            ],
            options={
                "ordering": ["name_last", "name_first", "name_middle"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "aha_school_id",
                    models.BigIntegerField(
                        help_text="The identifier used by the AHA for a school",
                        unique=True,
                        verbose_name="AHA school ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the school", max_length=200
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Dissertation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "aha_dissertation_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        help_text="The identifier used by the AHA for a dissertation",
                        null=True,
                        unique=True,
                        verbose_name="AHA dissertation ID",
                    ),
                ),
                ("title", models.CharField(max_length=2000)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1700, "The year must be after 1700"
                            ),
                            django.core.validators.MaxValueValidator(
                                2025, "The year must be the current year or before"
                            ),
                        ],
                    ),
                ),
                (
                    "aha_author_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA author ID",
                    ),
                ),
                (
                    "aha_school_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA school ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dissdb.scholar"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dissdb.school"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("chair", "chair"), ("reader", "reader")],
                        default="reader",
                        max_length=20,
                    ),
                ),
                (
                    "aha_scholar_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA scholar ID",
                    ),
                ),
                (
                    "aha_dissertation_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA dissertation ID",
                    ),
                ),
                (
                    "dissertation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dissdb.dissertation",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="dissdb.scholar"
                    ),
                ),
            ],
        ),
    ]
