# Generated by Django 4.1.3 on 2022-12-22 18:23
# Data migrations:
# https://docs.djangoproject.com/en/4.1/topics/migrations/#data-migrations
# Bulk data import:
# https://pmbaumgartner.github.io/blog/the-fastest-way-to-load-data-django-postgresql/

from django.db import migrations
import csv


def import_schools(apps, schema_editor):
    School = apps.get_model("dissdb", "School")
    to_import = []
    with open("aha-data/schools.csv", encoding="utf8") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            school = School(
                id=row["id"], aha_school_id=row["aha_school_id"], name=row["school"]
            )
            to_import.append(school)
    School.objects.bulk_create(to_import)


def truncate_schools(apps, schema_editor):
    School = apps.get_model("dissdb", "School")
    School.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("dissdb", "0001_model_school"),
    ]

    operations = [migrations.RunPython(import_schools, truncate_schools)]
