# Generated by Django 4.1.3 on 2022-12-23 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dissdb", "0006_seed_dissertations"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("chair", "chair"), ("reader", "reader")],
                        default="reader",
                        max_length=20,
                    ),
                ),
                (
                    "aha_scholar_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA scholar ID",
                    ),
                ),
                (
                    "aha_dissertation_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA dissertation ID",
                    ),
                ),
                (
                    "dissertation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dissdb.dissertation",
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dissdb.scholar",
                    ),
                ),
            ],
        ),
    ]
