# Generated by Django 5.2.5 on 2025-08-27 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissdb", "0009_alter_dissertation_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dissertation",
            name="year",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1700, "The year must be after 1700"
                    ),
                    django.core.validators.MaxValueValidator(
                        2025, "The year must be the current year or before"
                    ),
                ],
            ),
        ),
    ]
