# Generated by Django 5.2.5 on 2025-11-10 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissdb", "0010_alter_dissertation_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicateCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Confidence score from dedupe algorithm (0-1)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "is_duplicate",
                    models.BooleanField(
                        blank=True,
                        help_text="True if confirmed duplicate, False if not, None if not reviewed",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Review notes")),
                (
                    "scholar_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_candidate_1",
                        to="dissdb.scholar",
                    ),
                ),
                (
                    "scholar_2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_candidate_2",
                        to="dissdb.scholar",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score", "-created_at"],
                "unique_together": {("scholar_1", "scholar_2")},
            },
        ),
    ]
