# Generated by Django 5.2.5 on 2026-02-10 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissdb", "0012_merge_duplicate_scholars"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the source (organization, department, person, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("department", "Department"),
                            ("person", "Person"),
                            ("other", "Other"),
                        ],
                        help_text="Type of source",
                        max_length=20,
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Contact information or additional details",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about this source",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="dissertation",
            name="year",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1700, "The year must be after 1700"
                    ),
                    django.core.validators.MaxValueValidator(
                        2026, "The year must be the current year or before"
                    ),
                ],
            ),
        ),
    ]
