# Generated by Django 5.2.5 on 2026-02-10 21:03

import django.db.models.deletion
from django.db import migrations, models

def create_sources_and_populate(apps, schema_editor):
    """Create initial sources and assign to existing records"""
    Source = apps.get_model('dissdb', 'Source')
    School = apps.get_model('dissdb', 'School')
    Scholar = apps.get_model('dissdb', 'Scholar')
    Dissertation = apps.get_model('dissdb', 'Dissertation')
    CommitteeMember = apps.get_model('dissdb', 'CommitteeMember')
    
    # Create the AHA source
    aha_source = Source.objects.create(
        name='AHA Dataset',
        source_type='organization',
        notes='American Historical Association dissertation database - primary data source'
    )
    
    # Create other sources you might need
    manual_source = Source.objects.create(
        name='Manual Entry',
        source_type='other',
        notes='Manually entered data'
    )

    department_source = Source.objects.create(
        name='Department Data',
        source_type='department',
        notes='Dissertation data sourced from an academic department'
    )
    
    crowdsourced_source = Source.objects.create(
        name='Crowdsourced Contribution',
        source_type='person',
        notes='Crowdsourced data from scholars'
    )
    
    # Assign AHA source to all existing records
    School.objects.all().update(source=aha_source)
    Scholar.objects.all().update(source=aha_source)
    Dissertation.objects.all().update(source=aha_source)
    CommitteeMember.objects.all().update(source=aha_source)
    
    print(f"Updated {School.objects.count()} schools")
    print(f"Updated {Scholar.objects.count()} scholars")
    print(f"Updated {Dissertation.objects.count()} dissertations")
    print(f"Updated {CommitteeMember.objects.count()} committee members")

def reverse_populate(apps, schema_editor):
    """Reverse migration - set all sources to NULL and delete Source records"""
    School = apps.get_model('dissdb', 'School')
    Scholar = apps.get_model('dissdb', 'Scholar')
    Dissertation = apps.get_model('dissdb', 'Dissertation')
    CommitteeMember = apps.get_model('dissdb', 'CommitteeMember')
    Source = apps.get_model('dissdb', 'Source')
    
    # Set all sources back to NULL
    School.objects.all().update(source=None)
    Scholar.objects.all().update(source=None)
    Dissertation.objects.all().update(source=None)
    CommitteeMember.objects.all().update(source=None)
    
    # Delete the sources we created
    Source.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("dissdb", "0013_source_alter_dissertation_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="committeemember",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="The source for this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dissdb.source",
            ),
        ),
        migrations.AddField(
            model_name="dissertation",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="The source for this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dissdb.source",
            ),
        ),
        migrations.AddField(
            model_name="scholar",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="The source for this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dissdb.source",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="source",
            field=models.ForeignKey(
                blank=True,
                help_text="The source for this record",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dissdb.source",
            ),
        ),
        migrations.RunPython(create_sources_and_populate, reverse_populate),
    ]
