# Generated by Django 5.2.5 on 2026-02-10 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissdb", "0014_committeemember_source_dissertation_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeemember",
            name="source",
            field=models.ForeignKey(
                default=1,
                help_text="The source for this record",
                on_delete=django.db.models.deletion.PROTECT,
                to="dissdb.source",
            ),
        ),
        migrations.AlterField(
            model_name="dissertation",
            name="source",
            field=models.ForeignKey(
                default=1,
                help_text="The source for this record",
                on_delete=django.db.models.deletion.PROTECT,
                to="dissdb.source",
            ),
        ),
        migrations.AlterField(
            model_name="scholar",
            name="source",
            field=models.ForeignKey(
                default=1,
                help_text="The source for this record",
                on_delete=django.db.models.deletion.PROTECT,
                to="dissdb.source",
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="source",
            field=models.ForeignKey(
                default=1,
                help_text="The source for this record",
                on_delete=django.db.models.deletion.PROTECT,
                to="dissdb.source",
            ),
        ),
    ]
