# Generated by Django 5.2.5 on 2026-02-10 21:34

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissdb", "0015_alter_committeemember_source_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCommitteeMember",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("chair", "chair"), ("reader", "reader")],
                        default="reader",
                        max_length=20,
                    ),
                ),
                (
                    "aha_scholar_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA scholar ID",
                    ),
                ),
                (
                    "aha_dissertation_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA dissertation ID",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "dissertation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.dissertation",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.scholar",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=1,
                        help_text="The source for this record",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical committee member",
                "verbose_name_plural": "historical committee members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDissertation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "aha_dissertation_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="The identifier used by the AHA for a dissertation",
                        null=True,
                        verbose_name="AHA dissertation ID",
                    ),
                ),
                ("title", models.CharField(max_length=2000)),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1700, "The year must be after 1700"
                            ),
                            django.core.validators.MaxValueValidator(
                                2026, "The year must be the current year or before"
                            ),
                        ],
                    ),
                ),
                (
                    "aha_author_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA author ID",
                    ),
                ),
                (
                    "aha_school_id",
                    models.BigIntegerField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="AHA school ID",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.scholar",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.school",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=1,
                        help_text="The source for this record",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical dissertation",
                "verbose_name_plural": "historical dissertations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDuplicateCandidate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Confidence score from dedupe algorithm (0-1)"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "is_duplicate",
                    models.BooleanField(
                        blank=True,
                        help_text="True if confirmed duplicate, False if not, None if not reviewed",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Review notes")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scholar_1",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.scholar",
                    ),
                ),
                (
                    "scholar_2",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.scholar",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical duplicate candidate",
                "verbose_name_plural": "historical duplicate candidates",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalScholar",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "aha_scholar_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="The identifier used by the AHA for a scholar",
                        null=True,
                        verbose_name="AHA scholar ID",
                    ),
                ),
                (
                    "aha_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        editable=False,
                        help_text="The name provided in the AHA dataset",
                        max_length=200,
                        null=True,
                        verbose_name="AHA name",
                    ),
                ),
                (
                    "name_first",
                    models.CharField(max_length=200, verbose_name="First name"),
                ),
                (
                    "name_middle",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=200,
                        verbose_name="Middle name",
                    ),
                ),
                (
                    "name_last",
                    models.CharField(max_length=200, verbose_name="Last name"),
                ),
                (
                    "name_suffix",
                    models.CharField(
                        blank=True, default=None, max_length=200, verbose_name="Suffix"
                    ),
                ),
                (
                    "orcid",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="ORCID in 0000-0000-0000-0000 format",
                        max_length=19,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\d{4}-\\d{4}-\\d{4}-\\d{4}"
                            )
                        ],
                        verbose_name="ORCID",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=1,
                        help_text="The source for this record",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical scholar",
                "verbose_name_plural": "historical scholars",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSchool",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "aha_school_id",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="The identifier used by the AHA for a school",
                        verbose_name="AHA school ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the school", max_length=200
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=1,
                        help_text="The source for this record",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical school",
                "verbose_name_plural": "historical schools",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSource",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the source (organization, department, person, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("department", "Department"),
                            ("person", "Person"),
                            ("other", "Other"),
                        ],
                        help_text="Type of source",
                        max_length=20,
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Contact information or additional details",
                    ),
                ),
                ("date_added", models.DateTimeField(blank=True, editable=False)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional notes about this source",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical source",
                "verbose_name_plural": "historical sources",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
