# Generated by Django 5.2.5 on 2026-02-25 19:11

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissdb", "0016_historicalcommitteemember_historicaldissertation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dissertation",
            name="abstract",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Abstract of the dissertation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaldissertation",
            name="abstract",
            field=models.TextField(
                blank=True,
                default=None,
                help_text="Abstract of the dissertation",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalscholar",
            name="affiliation",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The name of this scholar's current affiliation",
                max_length=200,
                null=True,
                verbose_name="Current University or other affiliation",
            ),
        ),
        migrations.AddField(
            model_name="scholar",
            name="affiliation",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The name of this scholar's current affiliation",
                max_length=200,
                null=True,
                verbose_name="Current University or other affiliation",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalDissertationLink",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("proquest", "ProQuest"),
                            ("institutional", "Institutional Repository"),
                            ("pdf", "PDF"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom label, e.g. 'GMU Institutional Repository'",
                        max_length=200,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "dissertation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.dissertation",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=1,
                        help_text="The source for this record",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical dissertation link",
                "verbose_name_plural": "historical dissertation links",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalScholarWebsite",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "website_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Website"),
                            ("department", "Department Profile"),
                            ("social media", "Social Media Profile"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom label, e.g. 'GMU Faculty Page'",
                        max_length=200,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.scholar",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=1,
                        help_text="The source for this record",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical scholar website",
                "verbose_name_plural": "historical scholar websites",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ScholarWebsite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "website_type",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Website"),
                            ("department", "Department Profile"),
                            ("social media", "Social Media Profile"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom label, e.g. 'GMU Faculty Page'",
                        max_length=200,
                    ),
                ),
                (
                    "scholar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websites",
                        to="dissdb.scholar",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        default=1,
                        help_text="The source for this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "ordering": ["website_type"],
            },
        ),
        migrations.CreateModel(
            name="DissertationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("proquest", "ProQuest"),
                            ("institutional", "Institutional Repository"),
                            ("pdf", "PDF"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional custom label, e.g. 'GMU Institutional Repository'",
                        max_length=200,
                    ),
                ),
                (
                    "dissertation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="dissdb.dissertation",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        default=1,
                        help_text="The source for this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "ordering": ["link_type"],
                "unique_together": {("dissertation", "url")},
            },
        ),
    ]
