# Generated by Django 5.2.5 on 2026-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissdb', '0017_dissertation_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscholar',
            name='name_middle',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='name_middle',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Middle name'),
        ),
    ]
