# Generated by Django 5.2.5 on 2026-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissdb', '0018_alter_historicalscholar_name_middle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalscholar',
            name='name_suffix',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Suffix'),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='name_suffix',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Suffix'),
        ),
    ]
