# Generated by Django 5.2.5 on 2026-03-05 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissdb', '0019_alter_historicalscholar_name_suffix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the department', max_length=200)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dissdb.school')),
            ],
        ),
        migrations.AddField(
            model_name='dissertation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dissdb.department'),
        ),
        migrations.AddField(
            model_name='historicaldissertation',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dissdb.department'),
        ),
    ]
