# Generated by Django 5.2.5 on 2026-03-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissdb', '0021_trigram_extension'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='committeemember',
            index=models.Index(fields=['role', 'scholar'], name='idx_cm_role_scholar'),
        ),
        migrations.AddIndex(
            model_name='committeemember',
            index=models.Index(fields=['role', 'dissertation'], name='idx_cm_role_diss'),
        ),
    ]
