# Generated by Django 5.2.5 on 2026-03-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissdb', '0022_accountrequest_historicalaccountrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the requester (used for rate limiting)', null=True),
        ),
        migrations.AddField(
            model_name='historicalaccountrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the requester (used for rate limiting)', null=True),
        ),
    ]
