# Generated by Django 5.2.5 on 2026-04-27 15:34

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dissdb", "0022_add_committeemember_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeographicEmphasis",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. North America, East Asia",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=200, unique=True
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        default=1,
                        help_text="The source for this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "geographic emphases",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="dissertation",
            name="geographic_emphases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Geographic tags for this dissertation",
                related_name="dissertations",
                to="dissdb.geographicemphasis",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalGeographicEmphasis",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. North America, East Asia",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=200
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=1,
                        help_text="The source for this record",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical geographic emphasis",
                "verbose_name_plural": "historical geographic emphases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalThematicEmphasis",
            fields=[
                ("id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. Political, Race, Gender",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=200
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=1,
                        help_text="The source for this record",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical thematic emphasis",
                "verbose_name_plural": "historical thematic emphases",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ThematicEmphasis",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Political, Race, Gender",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=200, unique=True
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        default=1,
                        help_text="The source for this record",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dissdb.source",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "thematic emphases",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="dissertation",
            name="thematic_emphases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Thematic tags for this dissertation",
                related_name="dissertations",
                to="dissdb.thematicemphasis",
            ),
        ),
    ]
