# Generated by Django 5.2.5 on 2026-04-28 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dissdb", "0023_geographicemphasis_dissertation_geographic_emphases_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geographicemphasis",
            name="aha_id",
            field=models.IntegerField(
                blank=True, help_text="Original AHA taxonomy ID", null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="geographicemphasis",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent geographic emphasis for hierarchical taxonomy",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="dissdb.geographicemphasis",
            ),
        ),
        migrations.AddField(
            model_name="historicalgeographicemphasis",
            name="aha_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Original AHA taxonomy ID",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalgeographicemphasis",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Parent geographic emphasis for hierarchical taxonomy",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dissdb.geographicemphasis",
            ),
        ),
        migrations.AddField(
            model_name="historicalthematicemphasis",
            name="aha_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Original AHA taxonomy ID",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalthematicemphasis",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Parent thematic emphasis for hierarchical taxonomy",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="dissdb.thematicemphasis",
            ),
        ),
        migrations.AddField(
            model_name="thematicemphasis",
            name="aha_id",
            field=models.IntegerField(
                blank=True, help_text="Original AHA taxonomy ID", null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="thematicemphasis",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent thematic emphasis for hierarchical taxonomy",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="dissdb.thematicemphasis",
            ),
        ),
    ]
